
export const UsersDataActionEnum  = {
    CLEAR_USERS_DATA: "CLEAR_USERS_DATA",
    SET_USERS_DATA: "SET_USERS_DATA",
    ADD_USER_DATA: "ADD_USERS_DATA",
    SET_ERROR_USERS_DATA: "SET_ERROR_USERS_DATA",
    SET_USERS_DATA_IS_LOADING: "SET_SELECTED_USER_IS_LOADING",
}
