// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Expression struct {
	ID             *string  `json:"id,omitempty"`
	Status         *int     `json:"status,omitempty"`
	Text           *string  `json:"text,omitempty"`
	DataCreated    *string  `json:"data_created,omitempty"`
	DataCalculated *string  `json:"data_calculated,omitempty"`
	Result         *float64 `json:"result,omitempty"`
}

type Mutation struct {
}

type Query struct {
}
